export const WORKFLOW_TEMPLATES = [
  {
    id: "customer_support",
    name: "Customer Support Automation",
    category: "support",
    description: "Route and respond to customer inquiries with automatic escalation to agents",
    icon: "💬",
    nodes: [
      { type: "trigger", label: "Customer Message Received", config: { voice_phrase: "support request" } },
      { type: "llm", label: "Classify Intent", config: { system_prompt: "Classify customer request as billing, technical, or general" } },
      { type: "condition", label: "Is Technical Issue?", config: { condition_expression: "intent === technical" } },
      { type: "action", label: "Create Support Ticket", config: { http_method: "POST" } },
      { type: "response", label: "Acknowledge & Route", config: { response_template: "Thank you for contacting support. Your ticket has been created." } },
      { type: "agent", label: "Specialized Support Agent", config: { agent_id: "x402_api_integrator" } },
      { type: "response", label: "Resolution Summary", config: { response_template: "Your issue has been resolved. Ticket ID: {{ticket_id}}" } },
      { type: "end", label: "Support Complete", config: {} },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3 },
      { from: 3, to: 4 },
      { from: 4, to: 5 },
      { from: 5, to: 6 },
      { from: 6, to: 7 },
    ],
  },
  {
    id: "lead_qualification",
    name: "Lead Qualification Pipeline",
    category: "sales",
    description: "Automatically qualify leads based on criteria and route to sales team",
    icon: "🎯",
    nodes: [
      { type: "trigger", label: "New Lead Submitted", config: { voice_phrase: "new lead" } },
      { type: "llm", label: "Extract Lead Info", config: { system_prompt: "Extract company, budget, timeline from lead data" } },
      { type: "condition", label: "Budget >= $50k?", config: { condition_expression: "budget >= 50000" } },
      { type: "action", label: "Create HubSpot Deal", config: { http_method: "POST" } },
      { type: "variable", label: "Mark as Hot Lead", config: { variable_name: "lead_quality", variable_value: "hot" } },
      { type: "agent", label: "Sales Qualification Agent", config: { agent_id: "x402_data_analyst" } },
      { type: "webhook_action", label: "Notify Sales Team", config: { http_method: "POST" } },
      { type: "end", label: "Lead Qualified", config: {} },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3 },
      { from: 3, to: 4 },
      { from: 4, to: 5 },
      { from: 5, to: 6 },
      { from: 6, to: 7 },
    ],
  },
  {
    id: "content_generation",
    name: "Content Generation Pipeline",
    category: "content",
    description: "Generate, review, and publish content automatically",
    icon: "✍️",
    nodes: [
      { type: "trigger", label: "Content Request Received", config: { voice_phrase: "generate content" } },
      { type: "variable", label: "Set Content Type", config: { variable_name: "content_type", variable_value: "blog_post" } },
      { type: "agent", label: "Content Creator Agent", config: { agent_id: "x402_content_creator" } },
      { type: "condition", label: "Meets Quality Threshold?", config: { condition_expression: "quality_score > 0.8" } },
      { type: "action", label: "Post to CMS", config: { http_method: "POST" } },
      { type: "response", label: "Publish Confirmation", config: { response_template: "Content published successfully" } },
      { type: "end", label: "Complete", config: {} },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3 },
      { from: 3, to: 4 },
      { from: 4, to: 5 },
      { from: 5, to: 6 },
    ],
  },
  {
    id: "data_processing",
    name: "Data Processing & Analysis",
    category: "data",
    description: "Ingest, process, and analyze data with automated reporting",
    icon: "📊",
    nodes: [
      { type: "webhook_trigger", label: "Data Upload Received", config: { webhook_url: "https://api.example.com/data" } },
      { type: "agent", label: "Data Analyst Agent", config: { agent_id: "x402_data_analyst" } },
      { type: "llm", label: "Generate Report Summary", config: { system_prompt: "Summarize data analysis findings" } },
      { type: "action", label: "Store Results", config: { http_method: "POST" } },
      { type: "webhook_action", label: "Send Report", config: { http_method: "POST" } },
      { type: "response", label: "Analysis Complete", config: { response_template: "Data analysis complete. Report available." } },
      { type: "end", label: "Done", config: {} },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3 },
      { from: 3, to: 4 },
      { from: 4, to: 5 },
      { from: 5, to: 6 },
    ],
  },
  {
    id: "compliance_check",
    name: "Compliance Review Workflow",
    category: "compliance",
    description: "Automated compliance verification and policy enforcement",
    icon: "⚖️",
    nodes: [
      { type: "trigger", label: "Document Submitted", config: { voice_phrase: "compliance review" } },
      { type: "agent", label: "Compliance Reviewer Agent", config: { agent_id: "x402_compliance_reviewer" } },
      { type: "condition", label: "Passes Compliance?", config: { condition_expression: "compliance_status === passed" } },
      { type: "response", label: "Approval Granted", config: { response_template: "Document approved for use" } },
      { type: "response", label: "Rejection Notice", config: { response_template: "Document requires revisions" } },
      { type: "action", label: "Log Audit Trail", config: { http_method: "POST" } },
      { type: "end", label: "Review Complete", config: {} },
    ],
    edges: [
      { from: 0, to: 1 },
      { from: 1, to: 2 },
      { from: 2, to: 3 },
      { from: 2, to: 4 },
      { from: 3, to: 5 },
      { from: 4, to: 5 },
      { from: 5, to: 6 },
    ],
  },
];

export function getTemplatesByCategory(category) {
  return category === "all" ? WORKFLOW_TEMPLATES : WORKFLOW_TEMPLATES.filter((t) => t.category === category);
}

export function getTemplate(id) {
  return WORKFLOW_TEMPLATES.find((t) => t.id === id);
}